// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/razpravljalnica.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST   OpType = 0 // add a message to a topic
	OpType_OP_LIKE   OpType = 1 // like a message
	OpType_OP_DELETE OpType = 2 // delete a message
	OpType_OP_UPDATE OpType = 3 // update a message
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
		2: "OP_DELETE",
		3: "OP_UPDATE",
	}
	OpType_value = map[string]int32{
		"OP_POST":   0,
		"OP_LIKE":   1,
		"OP_DELETE": 2,
		"OP_UPDATE": 3,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_api_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

// //////////////////////////////////////////////////////////////////////////////
// Basic data types
// //////////////////////////////////////////////////////////////////////////////
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_api_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who liked the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_api_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubscriptionsResponse) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *DeleteMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // new text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *UpdateMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who posted the like
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message (0 from beggining)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // max number of messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // Single topic per subscription
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token generated by the head used to authorize the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeTopicRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // Single topic per subscription
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterSubscriptionTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSubscriptionTokenRequest) Reset() {
	*x = RegisterSubscriptionTokenRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSubscriptionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSubscriptionTokenRequest) ProtoMessage() {}

func (x *RegisterSubscriptionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSubscriptionTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterSubscriptionTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterSubscriptionTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterSubscriptionTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterSubscriptionTokenRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // monotonically increasing event number
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`                   // type of event
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"` // timestamp of the event
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_api_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type ReplicationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`
	User           *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // if CreateUser
	Topic          *Topic                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`     // if CreateTopic
	Message        *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // if Post/Update/Delete/LikeMessage
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *ReplicationRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ReplicationRequest) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *ReplicationRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ReplicationRequest) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *ReplicationRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ReplicationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AckSequenceNumber int64                  `protobuf:"varint,1,opt,name=ack_sequence_number,json=ackSequenceNumber,proto3" json:"ack_sequence_number,omitempty"` // potrjeni seqID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{23}
}

func (x *ReplicationResponse) GetAckSequenceNumber() int64 {
	if x != nil {
		return x.AckSequenceNumber
	}
	return 0
}

// Chain reconfiguration messages
type UpdateChainTopologyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewNextAddress  string                 `protobuf:"bytes,1,opt,name=new_next_address,json=newNextAddress,proto3" json:"new_next_address,omitempty"`     // New successor node address (empty if this becomes tail)
	NewPrevAddress  string                 `protobuf:"bytes,2,opt,name=new_prev_address,json=newPrevAddress,proto3" json:"new_prev_address,omitempty"`     // New predecessor node address (for sync purposes)
	LastAckSequence int64                  `protobuf:"varint,3,opt,name=last_ack_sequence,json=lastAckSequence,proto3" json:"last_ack_sequence,omitempty"` // Last sequence number acknowledged by predecessor
	IsHead          bool                   `protobuf:"varint,4,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"`                              // True if this node is now head
	IsTail          bool                   `protobuf:"varint,5,opt,name=is_tail,json=isTail,proto3" json:"is_tail,omitempty"`                              // True if this node is now tail
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateChainTopologyRequest) Reset() {
	*x = UpdateChainTopologyRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChainTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChainTopologyRequest) ProtoMessage() {}

func (x *UpdateChainTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChainTopologyRequest.ProtoReflect.Descriptor instead.
func (*UpdateChainTopologyRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateChainTopologyRequest) GetNewNextAddress() string {
	if x != nil {
		return x.NewNextAddress
	}
	return ""
}

func (x *UpdateChainTopologyRequest) GetNewPrevAddress() string {
	if x != nil {
		return x.NewPrevAddress
	}
	return ""
}

func (x *UpdateChainTopologyRequest) GetLastAckSequence() int64 {
	if x != nil {
		return x.LastAckSequence
	}
	return 0
}

func (x *UpdateChainTopologyRequest) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *UpdateChainTopologyRequest) GetIsTail() bool {
	if x != nil {
		return x.IsTail
	}
	return false
}

type SyncDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSequence  int64                  `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"` // Start syncing from this sequence number (exclusive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataRequest) Reset() {
	*x = SyncDataRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataRequest) ProtoMessage() {}

func (x *SyncDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataRequest.ProtoReflect.Descriptor instead.
func (*SyncDataRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{25}
}

func (x *SyncDataRequest) GetFromSequence() int64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

type SyncDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*ReplicationRequest  `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"` // All operations from sequence onwards
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataResponse) Reset() {
	*x = SyncDataResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataResponse) ProtoMessage() {}

func (x *SyncDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataResponse.ProtoReflect.Descriptor instead.
func (*SyncDataResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{26}
}

func (x *SyncDataResponse) GetOperations() []*ReplicationRequest {
	if x != nil {
		return x.Operations
	}
	return nil
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	AllNodes      []*NodeInfo            `protobuf:"bytes,3,rep,name=all_nodes,json=allNodes,proto3" json:"all_nodes,omitempty"` // All nodes in the chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{27}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *GetClusterStateResponse) GetAllNodes() []*NodeInfo {
	if x != nil {
		return x.AllNodes
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	IsHead        bool                   `protobuf:"varint,2,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"` // True if this is the head node
	IsTail        bool                   `protobuf:"varint,3,opt,name=is_tail,json=isTail,proto3" json:"is_tail,omitempty"` // True if this is the tail node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{28}
}

func (x *RegisterNodeRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RegisterNodeRequest) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *RegisterNodeRequest) GetIsTail() bool {
	if x != nil {
		return x.IsTail
	}
	return false
}

type SubscriptionResponsibilityResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Assignments   []*NodeResponsibilityAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponsibilityResponse) Reset() {
	*x = SubscriptionResponsibilityResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponsibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponsibilityResponse) ProtoMessage() {}

func (x *SubscriptionResponsibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponsibilityResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponsibilityResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{29}
}

func (x *SubscriptionResponsibilityResponse) GetAssignments() []*NodeResponsibilityAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type NodeResponsibilityAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	ModuloIndex   int32                  `protobuf:"varint,2,opt,name=modulo_index,json=moduloIndex,proto3" json:"modulo_index,omitempty"` // This node handles users where userID % total_nodes == modulo_index
	TotalNodes    int32                  `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`    // Total number of nodes in the chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponsibilityAssignment) Reset() {
	*x = NodeResponsibilityAssignment{}
	mi := &file_api_razpravljalnica_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponsibilityAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponsibilityAssignment) ProtoMessage() {}

func (x *NodeResponsibilityAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponsibilityAssignment.ProtoReflect.Descriptor instead.
func (*NodeResponsibilityAssignment) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{30}
}

func (x *NodeResponsibilityAssignment) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeResponsibilityAssignment) GetModuloIndex() int32 {
	if x != nil {
		return x.ModuloIndex
	}
	return 0
}

func (x *NodeResponsibilityAssignment) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

type ReportNodeFailureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FailedNodeId   string                 `protobuf:"bytes,1,opt,name=failed_node_id,json=failedNodeId,proto3" json:"failed_node_id,omitempty"`       // ID of the node that failed
	ReporterNodeId string                 `protobuf:"bytes,2,opt,name=reporter_node_id,json=reporterNodeId,proto3" json:"reporter_node_id,omitempty"` // ID of the node reporting the failure
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportNodeFailureRequest) Reset() {
	*x = ReportNodeFailureRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeFailureRequest) ProtoMessage() {}

func (x *ReportNodeFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeFailureRequest.ProtoReflect.Descriptor instead.
func (*ReportNodeFailureRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{31}
}

func (x *ReportNodeFailureRequest) GetFailedNodeId() string {
	if x != nil {
		return x.FailedNodeId
	}
	return ""
}

func (x *ReportNodeFailureRequest) GetReporterNodeId() string {
	if x != nil {
		return x.ReporterNodeId
	}
	return ""
}

type AssignSubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSubscriptionNodeRequest) Reset() {
	*x = AssignSubscriptionNodeRequest{}
	mi := &file_api_razpravljalnica_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSubscriptionNodeRequest) ProtoMessage() {}

func (x *AssignSubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*AssignSubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{32}
}

func (x *AssignSubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignSubscriptionNodeRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type AssignSubscriptionNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // Assigned node for this subscription
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSubscriptionNodeResponse) Reset() {
	*x = AssignSubscriptionNodeResponse{}
	mi := &file_api_razpravljalnica_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSubscriptionNodeResponse) ProtoMessage() {}

func (x *AssignSubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_razpravljalnica_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*AssignSubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_razpravljalnica_proto_rawDescGZIP(), []int{33}
}

func (x *AssignSubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_api_razpravljalnica_proto protoreflect.FileDescriptor

const file_api_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"\x19api/razpravljalnica.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"3\n" +
	"\x18ListSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\x19ListSubscriptionsResponse\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"i\n" +
	"\x14DeleteMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"}\n" +
	"\x14UpdateMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"g\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"l\n" +
	" RegisterSubscriptionTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x03R\atopicId\"\xcb\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\"\xf3\x01\n" +
	"\x12ReplicationRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x12)\n" +
	"\x04user\x18\x03 \x01(\v2\x15.razpravljalnica.UserR\x04user\x12,\n" +
	"\x05topic\x18\x04 \x01(\v2\x16.razpravljalnica.TopicR\x05topic\x122\n" +
	"\amessage\x18\x05 \x01(\v2\x18.razpravljalnica.MessageR\amessage\"E\n" +
	"\x13ReplicationResponse\x12.\n" +
	"\x13ack_sequence_number\x18\x01 \x01(\x03R\x11ackSequenceNumber\"\xce\x01\n" +
	"\x1aUpdateChainTopologyRequest\x12(\n" +
	"\x10new_next_address\x18\x01 \x01(\tR\x0enewNextAddress\x12(\n" +
	"\x10new_prev_address\x18\x02 \x01(\tR\x0enewPrevAddress\x12*\n" +
	"\x11last_ack_sequence\x18\x03 \x01(\x03R\x0flastAckSequence\x12\x17\n" +
	"\ais_head\x18\x04 \x01(\bR\x06isHead\x12\x17\n" +
	"\ais_tail\x18\x05 \x01(\bR\x06isTail\"6\n" +
	"\x0fSyncDataRequest\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x03R\ffromSequence\"W\n" +
	"\x10SyncDataResponse\x12C\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2#.razpravljalnica.ReplicationRequestR\n" +
	"operations\"\xaf\x01\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x126\n" +
	"\tall_nodes\x18\x03 \x03(\v2\x19.razpravljalnica.NodeInfoR\ballNodes\"v\n" +
	"\x13RegisterNodeRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\x12\x17\n" +
	"\ais_head\x18\x02 \x01(\bR\x06isHead\x12\x17\n" +
	"\ais_tail\x18\x03 \x01(\bR\x06isTail\"u\n" +
	"\"SubscriptionResponsibilityResponse\x12O\n" +
	"\vassignments\x18\x01 \x03(\v2-.razpravljalnica.NodeResponsibilityAssignmentR\vassignments\"\x91\x01\n" +
	"\x1cNodeResponsibilityAssignment\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\x12!\n" +
	"\fmodulo_index\x18\x02 \x01(\x05R\vmoduloIndex\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x05R\n" +
	"totalNodes\"j\n" +
	"\x18ReportNodeFailureRequest\x12$\n" +
	"\x0efailed_node_id\x18\x01 \x01(\tR\ffailedNodeId\x12(\n" +
	"\x10reporter_node_id\x18\x02 \x01(\tR\x0ereporterNodeId\"S\n" +
	"\x1dAssignSubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\"O\n" +
	"\x1eAssignSubscriptionNodeResponse\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node*@\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02\x12\r\n" +
	"\tOP_UPDATE\x10\x032\xe4\b\n" +
	"\fMessageBoard\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12A\n" +
	"\aGetUser\x12\x1f.razpravljalnica.GetUserRequest\x1a\x15.razpravljalnica.User\x12j\n" +
	"\x11ListSubscriptions\x12).razpravljalnica.ListSubscriptionsRequest\x1a*.razpravljalnica.ListSubscriptionsResponse\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12P\n" +
	"\rUpdateMessage\x12%.razpravljalnica.UpdateMessageRequest\x1a\x18.razpravljalnica.Message\x12N\n" +
	"\rDeleteMessage\x12%.razpravljalnica.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse\x12f\n" +
	"\x19RegisterSubscriptionToken\x121.razpravljalnica.RegisterSubscriptionTokenRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x012\xa2\x02\n" +
	"\x12ReplicationService\x12_\n" +
	"\x12ReplicateOperation\x12#.razpravljalnica.ReplicationRequest\x1a$.razpravljalnica.ReplicationResponse\x12Z\n" +
	"\x13UpdateChainTopology\x12+.razpravljalnica.UpdateChainTopologyRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\bSyncData\x12 .razpravljalnica.SyncDataRequest\x1a!.razpravljalnica.SyncDataResponse2\xf2\x03\n" +
	"\fControlPlane\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12L\n" +
	"\fRegisterNode\x12$.razpravljalnica.RegisterNodeRequest\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x1dGetSubscriptionResponsibility\x12\x16.google.protobuf.Empty\x1a3.razpravljalnica.SubscriptionResponsibilityResponse\x12V\n" +
	"\x11ReportNodeFailure\x12).razpravljalnica.ReportNodeFailureRequest\x1a\x16.google.protobuf.Empty\x12y\n" +
	"\x16AssignSubscriptionNode\x12..razpravljalnica.AssignSubscriptionNodeRequest\x1a/.razpravljalnica.AssignSubscriptionNodeResponseB(Z&github.com/ela-lab/razpravljalnica/apib\x06proto3"

var (
	file_api_razpravljalnica_proto_rawDescOnce sync.Once
	file_api_razpravljalnica_proto_rawDescData []byte
)

func file_api_razpravljalnica_proto_rawDescGZIP() []byte {
	file_api_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_api_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_razpravljalnica_proto_rawDesc), len(file_api_razpravljalnica_proto_rawDesc)))
	})
	return file_api_razpravljalnica_proto_rawDescData
}

var file_api_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                                // 0: razpravljalnica.OpType
	(*User)(nil),                               // 1: razpravljalnica.User
	(*Topic)(nil),                              // 2: razpravljalnica.Topic
	(*Message)(nil),                            // 3: razpravljalnica.Message
	(*Like)(nil),                               // 4: razpravljalnica.Like
	(*NodeInfo)(nil),                           // 5: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),                  // 6: razpravljalnica.CreateUserRequest
	(*GetUserRequest)(nil),                     // 7: razpravljalnica.GetUserRequest
	(*ListSubscriptionsRequest)(nil),           // 8: razpravljalnica.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),          // 9: razpravljalnica.ListSubscriptionsResponse
	(*CreateTopicRequest)(nil),                 // 10: razpravljalnica.CreateTopicRequest
	(*PostMessageRequest)(nil),                 // 11: razpravljalnica.PostMessageRequest
	(*DeleteMessageRequest)(nil),               // 12: razpravljalnica.DeleteMessageRequest
	(*UpdateMessageRequest)(nil),               // 13: razpravljalnica.UpdateMessageRequest
	(*LikeMessageRequest)(nil),                 // 14: razpravljalnica.LikeMessageRequest
	(*ListTopicsResponse)(nil),                 // 15: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),                 // 16: razpravljalnica.GetMessagesRequest
	(*GetMessagesResponse)(nil),                // 17: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),              // 18: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),            // 19: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil),           // 20: razpravljalnica.SubscriptionNodeResponse
	(*RegisterSubscriptionTokenRequest)(nil),   // 21: razpravljalnica.RegisterSubscriptionTokenRequest
	(*MessageEvent)(nil),                       // 22: razpravljalnica.MessageEvent
	(*ReplicationRequest)(nil),                 // 23: razpravljalnica.ReplicationRequest
	(*ReplicationResponse)(nil),                // 24: razpravljalnica.ReplicationResponse
	(*UpdateChainTopologyRequest)(nil),         // 25: razpravljalnica.UpdateChainTopologyRequest
	(*SyncDataRequest)(nil),                    // 26: razpravljalnica.SyncDataRequest
	(*SyncDataResponse)(nil),                   // 27: razpravljalnica.SyncDataResponse
	(*GetClusterStateResponse)(nil),            // 28: razpravljalnica.GetClusterStateResponse
	(*RegisterNodeRequest)(nil),                // 29: razpravljalnica.RegisterNodeRequest
	(*SubscriptionResponsibilityResponse)(nil), // 30: razpravljalnica.SubscriptionResponsibilityResponse
	(*NodeResponsibilityAssignment)(nil),       // 31: razpravljalnica.NodeResponsibilityAssignment
	(*ReportNodeFailureRequest)(nil),           // 32: razpravljalnica.ReportNodeFailureRequest
	(*AssignSubscriptionNodeRequest)(nil),      // 33: razpravljalnica.AssignSubscriptionNodeRequest
	(*AssignSubscriptionNodeResponse)(nil),     // 34: razpravljalnica.AssignSubscriptionNodeResponse
	(*timestamppb.Timestamp)(nil),              // 35: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                      // 36: google.protobuf.Empty
}
var file_api_razpravljalnica_proto_depIdxs = []int32{
	35, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	3,  // 2: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	5,  // 3: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 4: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	3,  // 5: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	35, // 6: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	0,  // 7: razpravljalnica.ReplicationRequest.op:type_name -> razpravljalnica.OpType
	1,  // 8: razpravljalnica.ReplicationRequest.user:type_name -> razpravljalnica.User
	2,  // 9: razpravljalnica.ReplicationRequest.topic:type_name -> razpravljalnica.Topic
	3,  // 10: razpravljalnica.ReplicationRequest.message:type_name -> razpravljalnica.Message
	23, // 11: razpravljalnica.SyncDataResponse.operations:type_name -> razpravljalnica.ReplicationRequest
	5,  // 12: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	5,  // 13: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	5,  // 14: razpravljalnica.GetClusterStateResponse.all_nodes:type_name -> razpravljalnica.NodeInfo
	5,  // 15: razpravljalnica.RegisterNodeRequest.node:type_name -> razpravljalnica.NodeInfo
	31, // 16: razpravljalnica.SubscriptionResponsibilityResponse.assignments:type_name -> razpravljalnica.NodeResponsibilityAssignment
	5,  // 17: razpravljalnica.NodeResponsibilityAssignment.node:type_name -> razpravljalnica.NodeInfo
	5,  // 18: razpravljalnica.AssignSubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	6,  // 19: razpravljalnica.MessageBoard.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	7,  // 20: razpravljalnica.MessageBoard.GetUser:input_type -> razpravljalnica.GetUserRequest
	8,  // 21: razpravljalnica.MessageBoard.ListSubscriptions:input_type -> razpravljalnica.ListSubscriptionsRequest
	10, // 22: razpravljalnica.MessageBoard.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	11, // 23: razpravljalnica.MessageBoard.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	13, // 24: razpravljalnica.MessageBoard.UpdateMessage:input_type -> razpravljalnica.UpdateMessageRequest
	12, // 25: razpravljalnica.MessageBoard.DeleteMessage:input_type -> razpravljalnica.DeleteMessageRequest
	14, // 26: razpravljalnica.MessageBoard.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	19, // 27: razpravljalnica.MessageBoard.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	21, // 28: razpravljalnica.MessageBoard.RegisterSubscriptionToken:input_type -> razpravljalnica.RegisterSubscriptionTokenRequest
	36, // 29: razpravljalnica.MessageBoard.ListTopics:input_type -> google.protobuf.Empty
	16, // 30: razpravljalnica.MessageBoard.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	18, // 31: razpravljalnica.MessageBoard.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	23, // 32: razpravljalnica.ReplicationService.ReplicateOperation:input_type -> razpravljalnica.ReplicationRequest
	25, // 33: razpravljalnica.ReplicationService.UpdateChainTopology:input_type -> razpravljalnica.UpdateChainTopologyRequest
	26, // 34: razpravljalnica.ReplicationService.SyncData:input_type -> razpravljalnica.SyncDataRequest
	36, // 35: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	29, // 36: razpravljalnica.ControlPlane.RegisterNode:input_type -> razpravljalnica.RegisterNodeRequest
	36, // 37: razpravljalnica.ControlPlane.GetSubscriptionResponsibility:input_type -> google.protobuf.Empty
	32, // 38: razpravljalnica.ControlPlane.ReportNodeFailure:input_type -> razpravljalnica.ReportNodeFailureRequest
	33, // 39: razpravljalnica.ControlPlane.AssignSubscriptionNode:input_type -> razpravljalnica.AssignSubscriptionNodeRequest
	1,  // 40: razpravljalnica.MessageBoard.CreateUser:output_type -> razpravljalnica.User
	1,  // 41: razpravljalnica.MessageBoard.GetUser:output_type -> razpravljalnica.User
	9,  // 42: razpravljalnica.MessageBoard.ListSubscriptions:output_type -> razpravljalnica.ListSubscriptionsResponse
	2,  // 43: razpravljalnica.MessageBoard.CreateTopic:output_type -> razpravljalnica.Topic
	3,  // 44: razpravljalnica.MessageBoard.PostMessage:output_type -> razpravljalnica.Message
	3,  // 45: razpravljalnica.MessageBoard.UpdateMessage:output_type -> razpravljalnica.Message
	36, // 46: razpravljalnica.MessageBoard.DeleteMessage:output_type -> google.protobuf.Empty
	3,  // 47: razpravljalnica.MessageBoard.LikeMessage:output_type -> razpravljalnica.Message
	20, // 48: razpravljalnica.MessageBoard.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	36, // 49: razpravljalnica.MessageBoard.RegisterSubscriptionToken:output_type -> google.protobuf.Empty
	15, // 50: razpravljalnica.MessageBoard.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	17, // 51: razpravljalnica.MessageBoard.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	22, // 52: razpravljalnica.MessageBoard.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	24, // 53: razpravljalnica.ReplicationService.ReplicateOperation:output_type -> razpravljalnica.ReplicationResponse
	36, // 54: razpravljalnica.ReplicationService.UpdateChainTopology:output_type -> google.protobuf.Empty
	27, // 55: razpravljalnica.ReplicationService.SyncData:output_type -> razpravljalnica.SyncDataResponse
	28, // 56: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	36, // 57: razpravljalnica.ControlPlane.RegisterNode:output_type -> google.protobuf.Empty
	30, // 58: razpravljalnica.ControlPlane.GetSubscriptionResponsibility:output_type -> razpravljalnica.SubscriptionResponsibilityResponse
	36, // 59: razpravljalnica.ControlPlane.ReportNodeFailure:output_type -> google.protobuf.Empty
	34, // 60: razpravljalnica.ControlPlane.AssignSubscriptionNode:output_type -> razpravljalnica.AssignSubscriptionNodeResponse
	40, // [40:61] is the sub-list for method output_type
	19, // [19:40] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_razpravljalnica_proto_init() }
func file_api_razpravljalnica_proto_init() {
	if File_api_razpravljalnica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_razpravljalnica_proto_rawDesc), len(file_api_razpravljalnica_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_api_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_api_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_api_razpravljalnica_proto_msgTypes,
	}.Build()
	File_api_razpravljalnica_proto = out.File
	file_api_razpravljalnica_proto_goTypes = nil
	file_api_razpravljalnica_proto_depIdxs = nil
}
